### PR TITLE
Fix/geojson command

### LINKED ISSUE #181: always create geojson outputs with 'wsinfer run'
let's create geojson files at the end of each `wsinfer run` call. to do this, a few things will have to be done:

- put the geojson conversion functions into their own module `wsinfer/write_geojson.py`. we should use write_geojson.py instead of geojson.py so we don't have a name collision with the third-party `geojson` library.
- update `wsinfer run` to create geojson files at the end of the run. use the methods from `wsinfer/write_geojson.py`
- save geojsons to `RESULTS_DIR/model-outputs-geojson`
- rename `RESULTS_DIR/model-outputs` to `RESULTS_DIR/model-outputs-csv`
- also parallelize the geojson conversion over multiple cores (get the number of workers from `--num-workers` argument to `wsinfer run`). the geojson can take some time and we would speed it up tremendously by using multiple cores.

@swaradgat19 - would you like to tackle this?

### PR DESCRIPTION
**Pull request by swaradgat19**
fixes #181

### CODE REVIEW

**Comment by swaradgat19** [comment]
@kaczmarj So I made a separate branch and opened a PR (Including the fix #188 ). The `pytorch` test has passed, but the docker and the ubuntu tests haven't

**Comment by kaczmarj** [comment]
thanks @swaradgat19 - 

flake8 is failing with `wsinfer/write_geojson.py:92:89: E501 line too long (89 > 88 characters)` . seems that one line is just slightly too long :) you can run `black` on the file and it should fix it. so run `black wsinfer/` and then `flake8 wsinfer` and see if that helps.

i re-queued the failing tests -- maybe it was something random. i could not find any useful error messages in the ubuntu and docker tests.

**Comment by kaczmarj** [comment]
the docker and ubuntu tests are still failing. i will have to run those locally to see what is going on.

**Comment by kaczmarj** [comment]
@swaradgat19 - i think i figured out the failure. in 

https://github.com/SBU-BMI/wsinfer/blob/59c0f5c1fe44baab0a2e8616a8075ef238259bdd/.github/workflows/ci.yml#L107-L108

update the directory to use `model-outputs-csv`

same in https://github.com/SBU-BMI/wsinfer/blob/59c0f5c1fe44baab0a2e8616a8075ef238259bdd/.github/workflows/ci.yml#L121C1-L121C80

i am not sure why the windows tests are passing.... the directory seems incorrect. either i didn't write that test properly or the model-outputs directory is still being made somehow.

**Comment by swaradgat19** [comment]
Oh sure. I'll make the changes

**Comment by kaczmarj** [comment]
nice, the ubuntu test passes now!

flake8 is throwing the following error

```
wsinfer/write_geojson.py:92:89: E501 line too long (89 > 88 characters)
```

**Comment by swaradgat19** [comment]
I ran flake8 wsinfer, but it just gives me a bunch of errors saying the lines are long in multiple files. I'll shorten all and put in a commit. 

Also, since we're generating `model-outputs-geojson`, should we include that test in the yml as well?

**Comment by kaczmarj** [comment]
>I ran flake8 wsinfer, but it just gives me a bunch of errors saying the lines are long in multiple files. I'll shorten all and put in a commit.

i think you can shorten line 92 of `wsinfer/write_geojson.py` and we should be good.

yes we should add `model-outputs-geojson`. we don't necessarily have to test the contents now, but let's definitely test that the expected files are made.

in a future PR, we can add tests for the geojson conversion.

**Comment by kaczmarj** [comment]
excellent, all the tests passed! let me try this out on my machine to see how thing are. then i will merge. thanks so much @swaradgat19 !

**Comment by swaradgat19** [comment]
My pleasure! :) @kaczmarj

**Pull request merged**
